micronaut:
  application:
    name: pix
  server:
    port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep_alive_time: 1h
    max-inbound-message-size: 1024
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: ${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}

datasources:
  default:
    url: jdbc:postgresql://localhost:7075/Aplicacao
    driverClassName: org.postgresql.Driver
    username: root
    password: root

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true